// 练习课程数据 — 基于人教版七年级英语教材（上册+下册）
// 每个单元包含 sentences（句子练习）和 words（词汇练习）
const COURSES = [
  {
    id: 'weekly-5.22',
    name: '5月22日 每周过关',
    desc: '本周10个词汇 + 5个句子，挑战通关！',
    level: '每周过关',
    sentences: [
      { hint: '那个士兵正朝森林移动。', target: 'The soldier is moving towards the forest.' },
      { hint: '罗宾不知道那个人看起来是什么样子。', target: 'Robin did not know what that man looked like.' },
      { hint: '我会待在那儿直到你回来。', target: 'I will stay there until you come back.' },
      { hint: '你想加入哪个俱乐部？', target: 'What club do you want to join?' },
      { hint: '她昨天走了好长一段路。', target: 'She took a long walk yesterday.' },
    ],
    words: [
      { word: 'mark', phonetic: '/mɑːk/', meaning: 'n. 分数' },
      { word: 'mad', phonetic: '/mæd/', meaning: 'adj. 很生气的；疯的' },
      { word: 'badly', phonetic: '/ˈbædli/', meaning: 'adv. 严重地' },
      { word: 'afraid', phonetic: '/əˈfreɪd/', meaning: 'adj. 害怕的；担心的' },
      { word: 'enemy', phonetic: '/ˈenəmi/', meaning: 'n. 敌人' },
      { word: 'soldier', phonetic: '/ˈsəʊldʒə(r)/', meaning: 'n. 士兵' },
      { word: 'look', phonetic: '/lʊk/', meaning: 'n. 相貌；样子 v. 看起来' },
      { word: 'army', phonetic: '/ˈɑːmi/', meaning: 'n. 军队' },
      { word: 'enter', phonetic: '/ˈentə(r)/', meaning: 'v. 进入' },
      { word: 'towards', phonetic: '/təˈwɔːdz/', meaning: 'prep. 朝；向' },
    ]
  },
  {
    id: 'starter-1',
    name: 'Starter Unit 1: Hello!',
    desc: '打招呼、自我介绍、26个字母',
    level: '过渡单元',
    sentences: [
      { hint: '你好！', target: 'Hello!' },
      { hint: '嗨，雅明！', target: 'Hi, Yaming!' },
      { hint: '早上好，艾拉和艾玛！', target: 'Good morning, Ella and Emma!' },
      { hint: '你好，我叫艾玛。', target: 'Hello, my name is Emma.' },
      { hint: '你叫什么名字？', target: 'What is your name?' },
      { hint: '你怎样拼写你的名字？', target: 'How do you spell your name?' },
      { hint: '很高兴见到你。', target: 'Nice to meet you.' },
      { hint: '我也很高兴见到你。', target: 'Nice to meet you too.' },
      { hint: '你好吗？', target: 'How are you?' },
      { hint: '我很好，谢谢你。', target: 'I am fine, thank you.' },
      { hint: '我可以知道你的名字吗？', target: 'May I have your name?' },
      { hint: '同学们，请坐下。', target: 'Sit down, please.' },
      { hint: '大家好！', target: 'Hi, everyone!' },
      { hint: '再见！', target: 'Goodbye!' },
      { hint: '请互相问好。', target: 'Please say hi to each other.' },
    ],
    words: [
      { word: 'unit', phonetic: '/ˈjuːnɪt/', meaning: 'n. 单元' },
      { word: 'section', phonetic: '/ˈsekʃn/', meaning: 'n. 部分；地区' },
      { word: 'greet', phonetic: '/ɡriːt/', meaning: 'v. 招呼；问候' },
      { word: 'each', phonetic: '/iːtʃ/', meaning: 'adj. & pron. 每个；各自' },
      { word: 'other', phonetic: '/ˈʌðə(r)/', meaning: 'pron. 另外的人（或物）adj. 另外的' },
      { word: 'each other', phonetic: '', meaning: '互相；彼此' },
      { word: 'oh', phonetic: '/əʊ/', meaning: 'interj. 哦；啊' },
      { word: 'everyone', phonetic: '/ˈevriwʌn/', meaning: 'pron. 每人；所有人' },
      { word: 'start', phonetic: '/stɑːt/', meaning: 'v. 开始；着手' },
      { word: 'conversation', phonetic: '/ˌkɒnvəˈseɪʃn/', meaning: 'n. 谈话；交谈' },
      { word: 'spell', phonetic: '/spel/', meaning: 'v. 用字母拼；拼写' },
      { word: 'bell', phonetic: '/bel/', meaning: 'n. 铃（声）；钟（声）' },
    ]
  },
  {
    id: 'starter-2',
    name: 'Starter Unit 2: Keep Tidy!',
    desc: '描述物品、颜色、位置',
    level: '过渡单元',
    sentences: [
      { hint: '你书包里有什么？', target: 'What do you have in your schoolbag?' },
      { hint: '我有一顶帽子。', target: 'I have a cap.' },
      { hint: '我有一把尺子。', target: 'I have a ruler.' },
      { hint: '我有一个瓶子。', target: 'I have a bottle.' },
      { hint: '帽子是什么颜色的？', target: 'What colour is the cap?' },
      { hint: '它是红色的。', target: 'It is red.' },
      { hint: '裤子是什么颜色的？', target: 'What colour are the trousers?' },
      { hint: '它们是棕色的。', target: 'They are brown.' },
      { hint: '我找不到我的新帽子了。', target: 'I cannot find my new cap.' },
      { hint: '它在你的书桌下面。', target: 'It is under your desk.' },
      { hint: '你需要保持房间整洁。', target: 'You need to keep your room tidy.' },
      { hint: '书包在书桌上。', target: 'The schoolbag is on the desk.' },
      { hint: '一些书在盒子里。', target: 'Some books are in the box.' },
      { hint: '一副袜子在床下。', target: 'A pair of socks is under the bed.' },
      { hint: '它们在你的头上！', target: 'They are on your head!' },
    ],
    words: [
      { word: 'bottle', phonetic: '/ˈbɒtl/', meaning: 'n. 瓶子' },
      { word: 'eraser', phonetic: '/ɪˈreɪzə(r)/', meaning: 'n. 橡皮' },
      { word: 'key', phonetic: '/kiː/', meaning: 'n. 钥匙；关键' },
      { word: 'thing', phonetic: '/θɪŋ/', meaning: 'n. 东西；事情' },
      { word: 'need', phonetic: '/niːd/', meaning: 'v. & n. 需要' },
      { word: "You're welcome.", phonetic: '', meaning: '别客气；不用谢。' },
    ]
  },
  {
    id: 'starter-3',
    name: 'Starter Unit 3: Welcome!',
    desc: '农场动物、植物、数字',
    level: '过渡单元',
    sentences: [
      { hint: '这是什么？', target: 'What is this?' },
      { hint: '那是什么？', target: 'What is that?' },
      { hint: '它是一只猫。', target: 'It is a cat.' },
      { hint: '这些是什么？', target: 'What are these?' },
      { hint: '那些是什么？', target: 'What are those?' },
      { hint: '它们是胡萝卜植物。', target: 'They are carrot plants.' },
      { hint: '你能看到多少只兔子？', target: 'How many rabbits can you see?' },
      { hint: '他有多少只鸭子？', target: 'How many ducks does he have?' },
      { hint: '他有十四只鸭子。', target: 'He has fourteen ducks.' },
      { hint: '这是我叔叔的农场。', target: 'This is my uncle\'s farm.' },
      { hint: '它是一个大农场。', target: 'It is a big farm.' },
      { hint: '草是绿色的。', target: 'The grass is green.' },
      { hint: '你能看到许多种动物。', target: 'You can see many kinds of animals.' },
      { hint: '那是我叔叔的家。', target: 'That is my uncle\'s home.' },
      { hint: '你喜欢我叔叔的农场吗？', target: 'Do you like my uncle\'s farm?' },
    ],
    words: [
      { word: 'fun', phonetic: '/fʌn/', meaning: 'n. 乐趣；快乐 adj. 有趣的；使人快乐的' },
      { word: 'yard', phonetic: '/jɑːd/', meaning: 'n. 院子；园圃' },
      { word: 'carrot', phonetic: '/ˈkærət/', meaning: 'n. 胡萝卜' },
      { word: 'goose', phonetic: '/ɡuːs/', meaning: 'n. (pl. geese /ɡiːs/) 鹅' },
      { word: 'count', phonetic: '/kaʊnt/', meaning: 'v. 数数' },
      { word: 'another', phonetic: '/əˈnʌðə(r)/', meaning: 'adj. & pron. 另一；又一（人或事物）' },
      { word: 'else', phonetic: '/els/', meaning: 'adv. 其他的；别的' },
      { word: 'circle', phonetic: '/ˈsɜːkl/', meaning: 'v. 圈出 n. 圆形；圆圈' },
      { word: 'look at', phonetic: '', meaning: '看；瞧' },
    ]
  },
  {
    id: 'unit-1',
    name: 'Unit 1: You and Me',
    desc: '认识新朋友、个人信息、be动词',
    level: '正式单元',
    sentences: [
      { hint: '你来自哪里？', target: 'Where are you from?' },
      { hint: '你多大了？', target: 'How old are you?' },
      { hint: '你在哪个班？', target: 'What class are you in?' },
      { hint: '我叫彼得·布朗。', target: 'I am Peter Brown.' },
      { hint: '我十三岁。', target: 'I am thirteen years old.' },
      { hint: '我来自中国。', target: 'I am from China.' },
      { hint: '他是我的新同学。', target: 'He is my new classmate.' },
      { hint: '她的名字叫艾玛。', target: 'Her name is Emma.' },
      { hint: '你最喜欢的动物是什么？', target: 'What is your favourite animal?' },
      { hint: '它是大熊猫。', target: 'It is the giant panda.' },
      { hint: '我最喜欢的国家是中国。', target: 'My favourite country is China.' },
      { hint: '你最喜欢的运动是什么？', target: 'What is your favourite sport?' },
      { hint: '我最喜欢的食物是面条。', target: 'My favourite food is noodles.' },
      { hint: '我们是好朋友。', target: 'We are good friends.' },
      { hint: '他来自哪里？', target: 'Where is he from?' },
    ],
    words: [
      { word: 'make friends', phonetic: '', meaning: '交朋友' },
      { word: 'get to know', phonetic: '', meaning: '认识；了解' },
      { word: 'full', phonetic: '/fʊl/', meaning: 'adj. 完整的；满的' },
      { word: 'full name', phonetic: '', meaning: '全名' },
      { word: 'grade', phonetic: '/ɡreɪd/', meaning: 'n. 年级；等级' },
      { word: 'last name', phonetic: '', meaning: '姓氏' },
      { word: 'classmate', phonetic: '/ˈklɑːsmeɪt/', meaning: 'n. 同班同学' },
      { word: 'class teacher', phonetic: '', meaning: '班主任' },
      { word: 'first name', phonetic: '', meaning: '名字' },
      { word: 'mistake', phonetic: '/mɪˈsteɪk/', meaning: 'n. 错误；失误' },
      { word: 'country', phonetic: '/ˈkʌntri/', meaning: 'n. 国家' },
      { word: 'same', phonetic: '/seɪm/', meaning: 'adj. 相同的' },
      { word: 'twin', phonetic: '/twɪn/', meaning: 'n. 双胞胎之一 adj. 双胞胎之一的' },
      { word: 'both', phonetic: '/bəʊθ/', meaning: 'adj. & pron. 两个；两个都' },
      { word: 'band', phonetic: '/bænd/', meaning: 'n. 乐队' },
      { word: 'pot', phonetic: '/pɒt/', meaning: 'n. 锅' },
      { word: 'a lot', phonetic: '', meaning: '很；非常' },
      { word: 'tofu', phonetic: '/ˈtəʊfuː/', meaning: 'n. 豆腐' },
      { word: 'parrot', phonetic: '/ˈpærət/', meaning: 'n. 鹦鹉' },
      { word: 'guitar', phonetic: '/ɡɪˈtɑː(r)/', meaning: 'n. 吉他' },
      { word: 'tennis', phonetic: '/ˈtenɪs/', meaning: 'n. 网球运动' },
      { word: 'page', phonetic: '/peɪdʒ/', meaning: 'n. 页面；（书刊或纸张）页' },
      { word: 'even', phonetic: '/ˈiːvn/', meaning: 'adv. 甚至；连；愈加' },
      { word: 'hey', phonetic: '/heɪ/', meaning: 'interj. 嘿；喂' },
      { word: 'play the guitar', phonetic: '', meaning: '弹吉他' },
      { word: 'would', phonetic: '/wʊd; wəd/', meaning: 'modal v. 想；将会' },
      { word: "would (') like to", phonetic: '', meaning: '表示愿意、喜欢' },
      { word: 'information', phonetic: '/ˌɪnfəˈmeɪʃn/', meaning: 'n. 信息；消息' },
      { word: 'hobby', phonetic: '/ˈhɒbi/', meaning: 'n. 业余爱好' },
      { word: 're', phonetic: '/riː/', meaning: 'prep. （用于回复电子邮件）关于；事由' },
    ]
  },
  {
    id: 'unit-2',
    name: 'Unit 2: We\'re Family!',
    desc: '家庭成员、描述家人、名词所有格',
    level: '正式单元',
    sentences: [
      { hint: '你的家庭是什么样的？', target: 'What is your family like?' },
      { hint: '这是我的妈妈。', target: 'This is my mum.' },
      { hint: '那是我的爸爸。', target: 'That is my dad.' },
      { hint: '她是我的姐姐。', target: 'She is my sister.' },
      { hint: '他是我的哥哥。', target: 'He is my brother.' },
      { hint: '她长什么样？', target: 'What does she look like?' },
      { hint: '她又高又瘦。', target: 'She is tall and thin.' },
      { hint: '他是做什么的？', target: 'What does he do?' },
      { hint: '他是一名医生。', target: 'He is a doctor.' },
      { hint: '我妈妈的名字叫李华。', target: 'My mum\'s name is Li Hua.' },
      { hint: '你家有几口人？', target: 'How many people are there in your family?' },
      { hint: '我家有四口人。', target: 'There are four people in my family.' },
      { hint: '我爱我的家庭。', target: 'I love my family.' },
      { hint: '他们非常友好。', target: 'They are very friendly.' },
      { hint: '你最喜欢的家庭成员是谁？', target: 'Who is your favourite family member?' },
    ],
    words: [
      { word: 'mean', phonetic: '/miːn/', meaning: 'v. 意思是；打算' },
      { word: 'husband', phonetic: '/ˈhʌzbənd/', meaning: 'n. 丈夫' },
      { word: 'bat', phonetic: '/bæt/', meaning: 'n. 球棒；球拍' },
      { word: 'ping-pong bat', phonetic: '', meaning: '乒乓球拍' },
      { word: 'play ping-pong', phonetic: '', meaning: '打乒乓球' },
      { word: 'together', phonetic: '/təˈɡeðə(r)/', meaning: 'adv. 在一起；共同' },
      { word: 'every day', phonetic: '', meaning: '每天' },
      { word: 'fishing rod', phonetic: '', meaning: '钓竿' },
      { word: 'spend', phonetic: '/spend/', meaning: 'v. 花（时间、钱等）' },
      { word: 'a lot of / lots of', phonetic: '', meaning: '大量；许多' },
      { word: 'really', phonetic: '/ˈriːəli/', meaning: 'adv. 非常；确实；真正地' },
      { word: 'member', phonetic: '/ˈmembə(r)/', meaning: 'n. 成员；会员' },
      { word: 'activity', phonetic: '/ækˈtɪvəti/', meaning: 'n. 活动' },
      { word: 'chess', phonetic: '/tʃes/', meaning: 'n. 国际象棋' },
      { word: 'Chinese chess', phonetic: '', meaning: '中国象棋' },
      { word: 'grandparent', phonetic: '/ˈɡrænpeərənt/', meaning: 'n. 祖父（母）；外祖父（母）' },
      { word: 'funny', phonetic: '/ˈfʌni/', meaning: 'adj. 好笑的；奇怪的' },
      { word: 'laugh', phonetic: '/lɑːf/', meaning: 'v. 笑；发笑 n. 笑声' },
      { word: 'different', phonetic: '/ˈdɪfrənt/', meaning: 'adj. 不同的' },
      { word: 'violin', phonetic: '/ˌvaɪəˈlɪn/', meaning: 'n. 小提琴' },
      { word: 'have fun', phonetic: '', meaning: '玩得高兴' },
      { word: 'hat', phonetic: '/hæt/', meaning: 'n. 帽子' },
      { word: 'handsome', phonetic: '/ˈhænsəm/', meaning: 'adj. 英俊的' },
      { word: 'knee', phonetic: '/niː/', meaning: 'n. 膝；膝盖' },
      { word: 'at night', phonetic: '', meaning: '在夜晚' },
      { word: 'in the middle', phonetic: '', meaning: '在中间' },
      { word: 'grandchild', phonetic: '/ˈɡræntʃaɪld/', meaning: 'n. (pl. grandchildren) （外）孙子；（外）孙女' },
      { word: 'son', phonetic: '/sʌn/', meaning: 'n. 儿子' },
      { word: 'hike', phonetic: '/haɪk/', meaning: 'v. & n. 远足；徒步旅行' },
      { word: 'go hiking', phonetic: '', meaning: '远足；徒步旅行' },
      { word: 'next to', phonetic: '', meaning: '紧邻；在……近旁' },
    ]
  },
  {
    id: 'unit-3',
    name: 'Unit 3: My School',
    desc: '学校场所、there be句型、方位介词',
    level: '正式单元',
    sentences: [
      { hint: '你的学校是什么样的？', target: 'What is your school like?' },
      { hint: '它很大很漂亮。', target: 'It is big and beautiful.' },
      { hint: '图书馆在哪里？', target: 'Where is the library?' },
      { hint: '它在教学楼旁边。', target: 'It is next to the teaching building.' },
      { hint: '操场上有许多学生。', target: 'There are many students on the playground.' },
      { hint: '教学楼前面有一棵大树。', target: 'There is a big tree in front of the teaching building.' },
      { hint: '餐厅在操场后面。', target: 'The dining hall is behind the playground.' },
      { hint: '教室里有四十张桌子。', target: 'There are forty desks in the classroom.' },
      { hint: '科学实验室在图书馆和办公室之间。', target: 'The science lab is between the library and the office.' },
      { hint: '我喜欢我的新学校。', target: 'I like my new school.' },
      { hint: '请给我介绍一下你的学校。', target: 'Please tell me about your school.' },
      { hint: '学校对面有一个公园。', target: 'There is a park across from the school.' },
      { hint: '墙上有一张地图。', target: 'There is a map on the wall.' },
      { hint: '你的教室是什么样的？', target: 'What is your classroom like?' },
      { hint: '它干净又明亮。', target: 'It is clean and bright.' },
    ],
    words: [
      { word: 'hall', phonetic: '/hɔːl/', meaning: 'n. 礼堂；大厅' },
      { word: 'dining', phonetic: '/ˈdaɪnɪŋ/', meaning: 'n. 餐厅' },
      { word: 'dining hall', phonetic: '', meaning: '餐厅' },
      { word: 'in front of', phonetic: '', meaning: '在……前面' },
      { word: 'building', phonetic: '/ˈbɪldɪŋ/', meaning: 'n. 建筑物；房子' },
      { word: 'across', phonetic: '/əˈkrɒs/', meaning: 'adv. & prep. 在（……）对面；横过' },
      { word: 'across from', phonetic: '', meaning: '在对面' },
      { word: 'centre', phonetic: '/ˈsentə(r)/', meaning: 'n. 中心；中央' },
      { word: 'gym', phonetic: '/dʒɪm/', meaning: 'n. 体育馆；健身房' },
      { word: 'field', phonetic: '/fiːld/', meaning: 'n. 场地；田地' },
      { word: 'sports field', phonetic: '', meaning: '运动场' },
      { word: 'office', phonetic: '/ˈɒfɪs/', meaning: 'n. 办公室' },
      { word: 'large', phonetic: '/lɑːdʒ/', meaning: 'adj. 大的；大号的' },
      { word: 'special', phonetic: '/ˈspeʃl/', meaning: 'adj. 特别的；特殊的' },
      { word: 'smart', phonetic: '/smɑːt/', meaning: 'adj. 智能的；聪明的' },
      { word: 'whiteboard', phonetic: '/ˈwaɪtbɔːd/', meaning: 'n. 白板；白色书写板' },
      { word: 'put up', phonetic: '', meaning: '张贴；搭建' },
      { word: 'important', phonetic: '/ɪmˈpɔːtnt/', meaning: 'adj. 重要的' },
      { word: 'notice', phonetic: '/ˈnəʊtɪs/', meaning: 'n. 通知；注意 v. 注意到；意识到' },
      { word: 'locker', phonetic: '/ˈlɒkə(r)/', meaning: 'n. 有锁存物柜；寄物柜' },
      { word: 'drawer', phonetic: '/drɔː(r)/', meaning: 'n. 抽屉' },
      { word: 'at the back (of)', phonetic: '', meaning: '在（……）后面' },
      { word: 'corner', phonetic: '/ˈkɔːnə(r)/', meaning: 'n. 角；墙角；街角' },
      { word: 'bookcase', phonetic: '/ˈbʊkkeɪs/', meaning: 'n. 书架；书柜' },
      { word: 'screen', phonetic: '/skriːn/', meaning: 'n. 屏幕；银幕' },
      { word: 'at school', phonetic: '', meaning: '在学校' },
      { word: 'different from', phonetic: '', meaning: '与……不一样' },
      { word: 'modern', phonetic: '/ˈmɒdn/', meaning: 'adj. 现代的；当代的' },
      { word: 'do exercises', phonetic: '', meaning: '做体操' },
      { word: 'amazing', phonetic: '/əˈmeɪzɪŋ/', meaning: 'adj. 令人惊奇（惊喜或惊叹）的' },
      { word: 'raise', phonetic: '/reɪz/', meaning: 'v. 使升高；提高' },
      { word: 'flag', phonetic: '/flæɡ/', meaning: 'n. 旗；旗帜' },
      { word: 'most', phonetic: '/məʊst/', meaning: 'adj. & pron. 大多数 adv. 最' },
      { word: 'change', phonetic: '/tʃeɪndʒ/', meaning: 'v. & n. 改变；变化' },
      { word: 'seat', phonetic: '/siːt/', meaning: 'n. 座位' },
      { word: 'delicious', phonetic: '/dɪˈlɪʃəs/', meaning: 'adj. 美味的；可口的' },
      { word: 'How about ...?', phonetic: '', meaning: '……怎么样？' },
      { word: 'yours', phonetic: '/jɔːz/', meaning: 'pron. 你的；您的' },
      { word: 'send', phonetic: '/send/', meaning: 'v. 发送；邮寄' },
      { word: 'similar', phonetic: '/ˈsɪmələ(r)/', meaning: 'adj. 类似的；相像的' },
      { word: 'similar to', phonetic: '', meaning: '类似的；相像的' },
      { word: 'sound', phonetic: '/saʊnd/', meaning: 'v. 听起来；好像 n. 声音；响声' },
      { word: 'bye for now', phonetic: '', meaning: '再见' },
    ]
  },
  {
    id: 'unit-4',
    name: 'Unit 4: My Favourite Subject',
    desc: '学科、喜好、连词and/but/because',
    level: '正式单元',
    sentences: [
      { hint: '你为什么喜欢这个学科？', target: 'Why do you like this subject?' },
      { hint: '我最喜欢的学科是英语。', target: 'My favourite subject is English.' },
      { hint: '我喜欢数学因为它很有趣。', target: 'I like maths because it is interesting.' },
      { hint: '我喜欢语文但是我不喜欢写作。', target: 'I like Chinese but I do not like writing.' },
      { hint: '你今天的课是什么？', target: 'What are your subjects today?' },
      { hint: '我们今天有语文、数学和英语。', target: 'We have Chinese, maths, and English today.' },
      { hint: '音乐课在下午。', target: 'Music class is in the afternoon.' },
      { hint: '历史是我最不喜欢的学科。', target: 'History is my least favourite subject.' },
      { hint: '科学很难但很有用。', target: 'Science is difficult but useful.' },
      { hint: '你能从不同学科中学到什么？', target: 'What can you learn from different subjects?' },
      { hint: '体育课非常有趣。', target: 'PE class is a lot of fun.' },
      { hint: '我喜欢画画。', target: 'I like drawing.' },
      { hint: '他最喜欢的学科是什么？', target: 'What is his favourite subject?' },
      { hint: '她喜欢音乐因为她喜欢唱歌。', target: 'She likes music because she likes singing.' },
      { hint: '我们每周有三节英语课。', target: 'We have three English classes every week.' },
    ],
    words: [
      { word: 'biology', phonetic: '/baɪˈɒlədʒi/', meaning: 'n. 生物学' },
      { word: 'IT', phonetic: '/ˌaɪ ˈtiː/', meaning: '信息技术' },
      { word: 'geography', phonetic: '/dʒiˈɒɡrəfi/', meaning: 'n. 地理（学）' },
      { word: 'history', phonetic: '/ˈhɪstri/', meaning: 'n. 历史；历史课' },
      { word: 'boring', phonetic: '/ˈbɔːrɪŋ/', meaning: 'adj. 乏味的；令人生厌的' },
      { word: 'useful', phonetic: '/ˈjuːsfl/', meaning: 'adj. 有用的；有益的' },
      { word: 'exciting', phonetic: '/ɪkˈsaɪtɪŋ/', meaning: 'adj. 令人激动的；使人兴奋的' },
      { word: 'past', phonetic: '/pɑːst/', meaning: 'n. 过去 adj. 过去的 prep. 在……之后' },
      { word: 'good with', phonetic: '', meaning: '灵巧的；善于应付……的' },
      { word: 'number', phonetic: '/ˈnʌmbə(r)/', meaning: 'n. 数字；号码' },
      { word: 'help sb with', phonetic: '', meaning: '帮助某人做（某事）' },
      { word: 'reason', phonetic: '/ˈriːzn/', meaning: 'n. 原因；理由' },
      { word: 'listen to', phonetic: '', meaning: '听；倾听' },
      { word: 'good at', phonetic: '', meaning: '擅长' },
      { word: 'remember', phonetic: '/rɪˈmembə(r)/', meaning: 'v. 记住；记起' },
      { word: 'as', phonetic: '/æz; əz/', meaning: 'prep. 如同；作为 conj. 当……时；由于' },
      { word: 'AM', phonetic: '/ˌeɪ ˈem/', meaning: '上午' },
      { word: 'PM', phonetic: '/ˌpiː ˈem/', meaning: '下午；午后' },
      { word: 'French', phonetic: '/frentʃ/', meaning: 'n. 法语 adj. 法国的；法国人的；法语的' },
      { word: 'excellent', phonetic: '/ˈeksələnt/', meaning: 'adj. 优秀的；极好的' },
      { word: 'instrument', phonetic: '/ˈɪnstrəmənt/', meaning: 'n. 乐器；器械；工具' },
      { word: 'singer', phonetic: '/ˈsɪŋə(r)/', meaning: 'n. 歌手' },
      { word: 'future', phonetic: '/ˈfjuːtʃə(r)/', meaning: 'n. 将来；未来' },
      { word: 'in the future', phonetic: '', meaning: '将来；未来' },
      { word: 'term', phonetic: '/tɜːm/', meaning: 'n. 学期' },
      { word: 'work out', phonetic: '', meaning: '计算出；解决' },
      { word: 'problem', phonetic: '/ˈprɒbləm/', meaning: 'n. 难题；困难' },
      { word: 'in class', phonetic: '', meaning: '课堂上' },
      { word: 'magic', phonetic: '/ˈmædʒɪk/', meaning: 'n. 魔法；魔力；魔术 adj. 有魔力的' },
      { word: 'life', phonetic: '/laɪf/', meaning: 'n. 生活；生命' },
      { word: 'scientist', phonetic: '/ˈsaɪəntɪst/', meaning: 'n. 科学家' },
    ]
  },
  {
    id: 'unit-5',
    name: 'Unit 5: Fun Clubs',
    desc: '学校社团、能力表达、情态动词can',
    level: '正式单元',
    sentences: [
      { hint: '你想加入什么社团？', target: 'What club do you want to join?' },
      { hint: '我想加入体育社团。', target: 'I want to join the sports club.' },
      { hint: '你会打乒乓球吗？', target: 'Can you play ping-pong?' },
      { hint: '是的，我会。', target: 'Yes, I can.' },
      { hint: '不，我不会。', target: 'No, I cannot.' },
      { hint: '她会拉小提琴。', target: 'She can play the violin.' },
      { hint: '他会弹吉他。', target: 'He can play the guitar.' },
      { hint: '我会打鼓。', target: 'I can play the drums.' },
      { hint: '你会下中国象棋吗？', target: 'Can you play Chinese chess?' },
      { hint: '我不会弹任何乐器。', target: 'I cannot play any musical instruments.' },
      { hint: '但是你唱歌唱得很好。', target: 'But you can sing well.' },
      { hint: '让我们放学后去音乐教室吧。', target: 'Let us go to the music room after school.' },
      { hint: '我想加入美术社团。', target: 'I want to join the art club.' },
      { hint: '你能有感情地朗读吗？', target: 'Can you read with feeling?' },
      { hint: '好消息！我们学校要开一个音乐社团。', target: 'Here is some good news! Our school wants to start a music club.' },
    ],
    words: [
      { word: 'club', phonetic: '/klʌb/', meaning: 'n. 俱乐部；社团' },
      { word: 'join', phonetic: '/dʒɔɪn/', meaning: 'v. 参加；加入' },
      { word: 'choose', phonetic: '/tʃuːz/', meaning: 'v. 选择；挑选' },
      { word: 'drama', phonetic: '/ˈdrɑːmə/', meaning: 'n. 戏剧；戏剧表演' },
      { word: 'play Chinese chess', phonetic: '', meaning: '下中国象棋' },
      { word: 'feeling', phonetic: '/ˈfiːlɪŋ/', meaning: 'n. 感觉；情感' },
      { word: 'news', phonetic: '/njuːz/', meaning: 'n. 消息；新闻' },
      { word: 'musical', phonetic: '/ˈmjuːzɪkl/', meaning: 'adj. 音乐的；有音乐天赋的' },
      { word: 'musical instrument', phonetic: '', meaning: '乐器' },
      { word: 'exactly', phonetic: '/ɪɡˈzæktli/', meaning: 'adv. 正是如此；准确地' },
      { word: 'drum', phonetic: '/drʌm/', meaning: 'n. 鼓' },
      { word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力；才能' },
      { word: 'paint', phonetic: '/peɪnt/', meaning: 'v. 用颜料画 n. 油漆；涂料' },
      { word: 'climb', phonetic: '/klaɪm/', meaning: 'v. 攀登；爬' },
      { word: 'more', phonetic: '/mɔː(r)/', meaning: 'adj. & pron. 更多（的）' },
      { word: 'act', phonetic: '/ækt/', meaning: 'v. 扮演；行动 n. （戏剧等）一幕；行动' },
      { word: 'act out', phonetic: '', meaning: '表演' },
      { word: 'at home', phonetic: '', meaning: '在家里' },
      { word: 'interested', phonetic: '/ˈɪntrəstɪd/', meaning: 'adj. 感兴趣的' },
      { word: 'interested in', phonetic: '', meaning: '对……感兴趣' },
      { word: 'nature', phonetic: '/ˈneɪtʃə(r)/', meaning: 'n. 自然界；大自然' },
      { word: 'beef', phonetic: '/biːf/', meaning: 'n. 牛肉' },
      { word: 'soon', phonetic: '/suːn/', meaning: 'adv. 不久；很快' },
      { word: 'than', phonetic: '/ðæn; ðən/', meaning: 'prep. & conj. 比' },
      { word: 'more than', phonetic: '', meaning: '多于' },
      { word: 'mind', phonetic: '/maɪnd/', meaning: 'n. 头脑；心思' },
      { word: 'fall', phonetic: '/fɔːl/', meaning: 'v. & n. 进入；掉落；跌倒 n. 秋天' },
      { word: 'fall in love with', phonetic: '', meaning: '爱上……' },
      { word: 'take photos', phonetic: '', meaning: '拍照' },
      { word: 'collect', phonetic: '/kəˈlekt/', meaning: 'v. 收集；采集' },
      { word: 'insect', phonetic: '/ˈɪnsekt/', meaning: 'n. 昆虫' },
      { word: 'discover', phonetic: '/dɪˈskʌvə(r)/', meaning: 'v. 发现；发觉' },
      { word: 'wildlife', phonetic: '/ˈwaɪldlaɪf/', meaning: 'n. 野生动物；野生生物' },
    ]
  },
  {
    id: 'unit-6',
    name: 'Unit 6: A Day in the Life',
    desc: '日常作息、时间表达、wh-疑问句',
    level: '正式单元',
    sentences: [
      { hint: '你怎样度过你的校园一天？', target: 'How do you spend your school day?' },
      { hint: '你几点起床？', target: 'What time do you get up?' },
      { hint: '我早上六点半起床。', target: 'I get up at six thirty in the morning.' },
      { hint: '你什么时候吃早餐？', target: 'When do you have breakfast?' },
      { hint: '我七点吃早餐。', target: 'I have breakfast at seven.' },
      { hint: '你怎样去学校？', target: 'How do you go to school?' },
      { hint: '我步行去学校。', target: 'I walk to school.' },
      { hint: '第一节课几点开始？', target: 'What time does the first class start?' },
      { hint: '你放学后做什么？', target: 'What do you do after school?' },
      { hint: '我通常做作业。', target: 'I usually do my homework.' },
      { hint: '你晚上几点睡觉？', target: 'What time do you go to bed at night?' },
      { hint: '我九点半睡觉。', target: 'I go to bed at nine thirty.' },
      { hint: '他的日常作息是什么样的？', target: 'What is his daily routine like?' },
      { hint: '他每天早上跑步。', target: 'He goes jogging every morning.' },
      { hint: '你需要好好利用你的时间。', target: 'You need to make good use of your time.' },
    ],
    words: [
      { word: 'make use of', phonetic: '', meaning: '使用……；利用……' },
      { word: 'quarter', phonetic: '/ˈkwɔːtə(r)/', meaning: 'n. 一刻钟；四等份之一' },
      { word: 'shower', phonetic: '/ˈʃaʊə(r)/', meaning: 'n. 淋浴；淋浴器 v. 洗淋浴' },
      { word: 'take a shower', phonetic: '', meaning: '淋浴' },
      { word: 'get dressed', phonetic: '', meaning: '穿衣服' },
      { word: 'brush', phonetic: '/brʌʃ/', meaning: 'v. （用刷子）刷 n. 刷子；画笔' },
      { word: 'tooth', phonetic: '/tuːθ/', meaning: 'n. (pl. teeth /tiːθ/) 牙齿' },
      { word: 'duty', phonetic: '/ˈdjuːti/', meaning: 'n. 值班；职责' },
      { word: 'on duty', phonetic: '', meaning: '值班' },
      { word: 'usually', phonetic: '/ˈjuːʒuəli/', meaning: 'adv. 通常地；一般地' },
      { word: 'get up', phonetic: '', meaning: '起床；站起' },
      { word: 'reporter', phonetic: '/rɪˈpɔːtə(r)/', meaning: 'n. 记者' },
      { word: 'around', phonetic: '/əˈraʊnd/', meaning: 'adv. & prep. 大约；环绕；到处' },
      { word: 'homework', phonetic: '/ˈhəʊmwɜːk/', meaning: 'n. 家庭作业' },
      { word: 'go to bed', phonetic: '', meaning: '上床睡觉' },
      { word: 'saying', phonetic: '/ˈseɪɪŋ/', meaning: 'n. 谚语；格言' },
      { word: 'rise', phonetic: '/raɪz/', meaning: 'v. 起床；升起；增长 n. 增加；增强' },
      { word: 'stay', phonetic: '/steɪ/', meaning: 'v. 停留；待' },
      { word: 'routine', phonetic: '/ruːˈtiːn/', meaning: 'n. 常规' },
      { word: 'restaurant', phonetic: '/ˈrestrɒnt/', meaning: 'n. 餐馆；餐厅' },
      { word: 'housework', phonetic: '/ˈhaʊswɜːk/', meaning: 'n. 家务劳动' },
      { word: 'while', phonetic: '/waɪl/', meaning: 'n. 一段时间 conj. 在……期间' },
      { word: 'weekend', phonetic: '/ˌwiːkˈend/', meaning: 'n. 周末' },
      { word: 'at weekends', phonetic: '', meaning: '在周末' },
      { word: 'daily', phonetic: '/ˈdeɪli/', meaning: 'adj. 每日的；日常的' },
      { word: 'daily routine', phonetic: '', meaning: '日常生活' },
      { word: 'only', phonetic: '/ˈəʊnli/', meaning: 'adv. 只；仅' },
      { word: 'break', phonetic: '/breɪk/', meaning: 'n. 休息；间断 v. （使）破碎；损坏' },
      { word: 'Finnish', phonetic: '/ˈfɪnɪʃ/', meaning: 'n. 芬兰语 adj. 芬兰的；芬兰人的' },
      { word: 'finish', phonetic: '/ˈfɪnɪʃ/', meaning: 'v. 结束；完成' },
      { word: 'hockey', phonetic: '/ˈhɒki/', meaning: 'n. 曲棍球' },
      { word: 'ice hockey', phonetic: '', meaning: '冰球运动；冰上曲棍球' },
      { word: 'already', phonetic: '/ɔːlˈredi/', meaning: 'adv. 已经；早已' },
      { word: 'dark', phonetic: '/dɑːk/', meaning: 'adj. 昏暗的；深色的' },
      { word: 'outside', phonetic: '/ˌaʊtˈsaɪd/', meaning: 'adv. & prep. 在（……）外面 adj. 外面的' },
      { word: 'part', phonetic: '/pɑːt/', meaning: 'n. 部分' },
      { word: 'everyday', phonetic: '/ˈevrideɪ/', meaning: 'adj. 每天的；日常的' },
      { word: 'prepare', phonetic: '/prɪˈpeə(r)/', meaning: 'v. 把……预备好；准备' },
      { word: 'prepare sth for', phonetic: '', meaning: '为……把某物准备好' },
    ]
  },
  {
    id: 'unit-7',
    name: 'Unit 7: Happy Birthday!',
    desc: '生日、日期、序数词、购物',
    level: '正式单元',
    sentences: [
      { hint: '你的生日是什么时候？', target: 'When is your birthday?' },
      { hint: '我的生日在十月一日。', target: 'My birthday is on October 1st.' },
      { hint: '你怎样庆祝生日？', target: 'How do you celebrate your birthday?' },
      { hint: '你多大了？', target: 'How old are you?' },
      { hint: '我今天十三岁了。', target: 'I am thirteen years old today.' },
      { hint: '生日快乐！', target: 'Happy birthday!' },
      { hint: '我想要一个生日蛋糕。', target: 'I want a birthday cake.' },
      { hint: '让我们一起庆祝你的生日吧。', target: 'Let us celebrate your birthday together.' },
      { hint: '这个多少钱？', target: 'How much is this?' },
      { hint: '我想为生日派对买东西。', target: 'I want to buy things for the birthday party.' },
      { hint: '你想要什么生日礼物？', target: 'What birthday gift do you want?' },
      { hint: '一月是一年中的第一个月。', target: 'January is the first month of the year.' },
      { hint: '你怎样让你的生日有意义？', target: 'How do you make your birthday meaningful?' },
      { hint: '我们为什么庆祝生日？', target: 'Why do we celebrate birthdays?' },
      { hint: '我想给我妈妈买一份礼物。', target: 'I want to buy a gift for my mum.' },
    ],
    words: [
      { word: 'celebrate', phonetic: '/ˈselɪbreɪt/', meaning: 'v. 庆祝；庆贺' },
      { word: 'surprise', phonetic: '/səˈpraɪz/', meaning: 'n. 惊奇；惊讶 v. 使感到意外' },
      { word: 'something', phonetic: '/ˈsʌmθɪŋ/', meaning: 'pron. 某事；某物' },
      { word: 'sale', phonetic: '/seɪl/', meaning: 'n. 出售；销售' },
      { word: 'kilo', phonetic: '/ˈkiːləʊ/', meaning: 'n. (pl. kilos) 千克；公斤' },
      { word: 'yogurt', phonetic: '/ˈjɒɡət/', meaning: 'n. 酸奶' },
      { word: 'total', phonetic: '/ˈtəʊtl/', meaning: 'n. 总数；合计 adj. 总的；全体的' },
      { word: 'price', phonetic: '/praɪs/', meaning: 'n. 价格' },
      { word: 'balloon', phonetic: '/bəˈluːn/', meaning: 'n. 气球' },
      { word: 'chocolate', phonetic: '/ˈtʃɒklət/', meaning: 'n. 巧克力' },
      { word: 'pizza', phonetic: '/ˈpiːtsə/', meaning: 'n. 比萨饼' },
      { word: 'list', phonetic: '/lɪst/', meaning: 'n. 名单；清单 v. 列表；列清单' },
      { word: 'own', phonetic: '/əʊn/', meaning: 'adj. & pron. 自己的；本人的' },
      { word: 'example', phonetic: '/ɪɡˈzɑːmpl/', meaning: 'n. 例子；范例' },
      { word: 'for example', phonetic: '', meaning: '例如' },
      { word: 'language', phonetic: '/ˈlæŋɡwɪdʒ/', meaning: 'n. 语言' },
      { word: 'international', phonetic: '/ˌɪntəˈnæʃnəl/', meaning: 'adj. 国际的' },
      { word: 'mark', phonetic: '/mɑːk/', meaning: 'v. 做记号；纪念；打分 n. 记号' },
      { word: 'national', phonetic: '/ˈnæʃnəl/', meaning: 'adj. 国家的；民族的' },
      { word: 'found', phonetic: '/faʊnd/', meaning: 'v. 创建；创立' },
      { word: 'meaningful', phonetic: '/ˈmiːnɪŋfl/', meaning: 'adj. 重要的；重大的' },
      { word: 'make a wish', phonetic: '', meaning: '许愿' },
      { word: 'celebration', phonetic: '/ˌselɪˈbreɪʃn/', meaning: 'n. 庆典；庆祝（活动）' },
      { word: 'post', phonetic: '/pəʊst/', meaning: 'n. 帖子；邮政 v. 邮寄；发布' },
      { word: 'contact', phonetic: '/ˈkɒntækt/', meaning: 'n. 联系；接触 v. 联系；联络' },
      { word: 'symbol', phonetic: '/ˈsɪmbl/', meaning: 'n. 象征；符号' },
      { word: 'take a photo', phonetic: '', meaning: '拍照' },
      { word: 'village', phonetic: '/ˈvɪlɪdʒ/', meaning: 'n. 村庄；村镇' },
      { word: 'grow', phonetic: '/ɡrəʊ/', meaning: 'v. 成长；长大；增长' },
      { word: 'blow', phonetic: '/bləʊ/', meaning: 'v. 吹；刮' },
      { word: 'blow out', phonetic: '', meaning: '吹灭' },
      { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', meaning: 'v. 享受……的乐趣；喜欢' },
      { word: 'height', phonetic: '/haɪt/', meaning: 'n. 身高；高度' },
      { word: 'later', phonetic: '/ˈleɪtə(r)/', meaning: 'adv. & adj. 以后（的）；后来（的）' },
      { word: 'next time', phonetic: '', meaning: '下次' },
      { word: 'whom', phonetic: '/huːm/', meaning: 'pron. 谁；什么人' },
    ]
  },
  // ========== 七年级下册 ==========
  {
    id: 'unit-8',
    name: 'Unit 1: Animal Friends (下)',
    desc: '谈论动物、描述动物、保护动物',
    level: '下册',
    sentences: [
      { hint: '你最喜欢的动物是什么？', target: 'What is your favourite animal?' },
      { hint: '我最喜欢的动物是猴子。', target: 'My favourite animal is the monkey.' },
      { hint: '你为什么喜欢猴子？', target: 'Why do you like monkeys?' },
      { hint: '因为它们聪明又有趣。', target: 'Because they are clever and funny.' },
      { hint: '企鹅来自哪里？', target: 'Where are penguins from?' },
      { hint: '它们来自南极洲。', target: 'They are from Antarctica.' },
      { hint: '你为什么不喜欢蛇？', target: 'Why do not you like snakes?' },
      { hint: '因为它们真的很吓人。', target: 'Because they are really scary.' },
      { hint: '大象看起来和其他动物很不同。', target: 'Elephants look very different from other animals.' },
      { hint: '它们有大耳朵和长鼻子。', target: 'They have large ears and long trunks.' },
      { hint: '大象能用鼻子搬运重物。', target: 'Elephants can pick up and carry heavy things with their trunks.' },
      { hint: '大象处于危险之中。', target: 'Elephants are in danger.' },
      { hint: '让我们拯救森林。', target: 'Let us save the forests.' },
      { hint: '它是什么样子的？', target: 'What does it look like?' },
      { hint: '它能做什么？', target: 'What can it do?' },
    ],
    words: [
      { word: 'fox', phonetic: '/fɒks/', meaning: 'n. 狐狸' },
      { word: 'giraffe', phonetic: '/dʒəˈrɑːf/', meaning: 'n. 长颈鹿' },
      { word: 'eagle', phonetic: '/ˈiːɡl/', meaning: 'n. 雕；鹰' },
      { word: 'wolf', phonetic: '/wʊlf/', meaning: 'n. (pl. wolves /wʊlvz/) 狼' },
      { word: 'penguin', phonetic: '/ˈpeŋɡwɪn/', meaning: 'n. 企鹅' },
      { word: 'care', phonetic: '/keə(r)/', meaning: 'n. 照顾；护理 v. 关心；在乎' },
      { word: 'take care of', phonetic: '', meaning: '照顾；处理' },
      { word: 'sandwich', phonetic: '/ˈsænwɪtʃ; ˈsænwɪdʒ/', meaning: 'n. 三明治' },
      { word: 'snake', phonetic: '/sneɪk/', meaning: 'n. 蛇' },
      { word: 'scary', phonetic: '/ˈskeəri/', meaning: 'adj. 吓人的；恐怖的' },
      { word: 'neck', phonetic: '/nek/', meaning: 'n. 脖子' },
      { word: 'guess', phonetic: '/ɡes/', meaning: 'v. 猜测；估计' },
      { word: 'shark', phonetic: '/ʃɑːk/', meaning: 'n. 鲨鱼' },
      { word: 'whale', phonetic: '/weɪl/', meaning: 'n. 鲸' },
      { word: 'huge', phonetic: '/hjuːdʒ/', meaning: 'adj. 巨大的；极多的' },
      { word: 'dangerous', phonetic: '/ˈdeɪndʒərəs/', meaning: 'adj. 危险的；有危害的' },
      { word: 'save', phonetic: '/seɪv/', meaning: 'v. 救；储蓄；保存' },
      { word: 'luck', phonetic: '/lʌk/', meaning: 'n. 幸运；运气' },
      { word: 'Thai', phonetic: '/taɪ/', meaning: 'adj. 泰国的；泰国人的 n. 泰国人；泰语' },
      { word: 'trunk', phonetic: '/trʌŋk/', meaning: 'n. 象鼻' },
      { word: 'pick', phonetic: '/pɪk/', meaning: 'v. 捡；摘' },
      { word: 'pick up', phonetic: '', meaning: '拿起；举起' },
      { word: 'carry', phonetic: '/ˈkæri/', meaning: 'v. 拿；提' },
      { word: 'playful', phonetic: '/ˈpleɪfl/', meaning: 'adj. 爱嬉戏的；爱玩的' },
      { word: 'swimmer', phonetic: '/ˈswɪmə(r)/', meaning: 'n. 游泳者' },
      { word: 'one another', phonetic: '', meaning: '互相' },
      { word: 'look after', phonetic: '', meaning: '照顾' },
      { word: 'culture', phonetic: '/ˈkʌltʃə(r)/', meaning: 'n. 文化；文明' },
      { word: 'however', phonetic: '/haʊˈevə(r)/', meaning: 'adv. 然而；不过' },
      { word: 'danger', phonetic: '/ˈdeɪndʒə(r)/', meaning: 'n. 危险' },
      { word: 'in danger', phonetic: '', meaning: '处于危险之中' },
      { word: 'forest', phonetic: '/ˈfɒrɪst/', meaning: 'n. 森林' },
      { word: 'cut down', phonetic: '', meaning: '砍伐；减少' },
      { word: 'too many', phonetic: '', meaning: '太多' },
      { word: 'kill', phonetic: '/kɪl/', meaning: 'v. 杀死；弄死' },
      { word: 'made of', phonetic: '', meaning: '由……制成的' },
      { word: 'ivory', phonetic: '/ˈaɪvəri/', meaning: 'n. 象牙' },
      { word: 'friendly', phonetic: '/ˈfrendli/', meaning: 'adj. 友好的' },
      { word: 'quite', phonetic: '/kwaɪt/', meaning: 'adv. 相当；完全' },
      { word: 'quite a', phonetic: '', meaning: '相当；非常' },
      { word: 'not … at all', phonetic: '', meaning: '一点也不；完全不' },
      { word: 'fur', phonetic: '/fɜː(r)/', meaning: 'n. （动物浓厚的）软毛' },
      { word: 'blind', phonetic: '/blaɪnd/', meaning: 'adj. 瞎的；失明的' },
      { word: 'hearing', phonetic: '/ˈhɪərɪŋ/', meaning: 'n. 听力；听觉' },
    ]
  },
  {
    id: 'unit-9',
    name: 'Unit 2: No Rules, No Order (下)',
    desc: '规则、情态动词can/have to/must',
    level: '下册',
    sentences: [
      { hint: '你在学校必须遵守什么规则？', target: 'What rules do you have at school?' },
      { hint: '上课不要迟到。', target: 'Do not be late for class.' },
      { hint: '不要在走廊里跑。', target: 'Do not run in the hallways.' },
      { hint: '我们不能在课堂上吃零食。', target: 'We cannot eat snacks in class.' },
      { hint: '我们必须穿校服。', target: 'We have to wear the uniform.' },
      { hint: '我们可以喝水吗？', target: 'Can we drink water?' },
      { hint: '不，我们不能在课堂上使用手机。', target: 'No, we cannot use our phones in class.' },
      { hint: '你们必须把手机关掉。', target: 'You must turn them off.' },
      { hint: '不要插队。', target: 'Do not jump the queue.' },
      { hint: '在图书馆我们必须保持安静。', target: 'We must keep quiet in the library.' },
      { hint: '规则能帮助你成为更好的人。', target: 'Rules can help you become a better person.' },
      { hint: '生活中有太多规则了！', target: 'There are too many rules in my life!' },
      { hint: '我每天必须先做完作业。', target: 'I have to finish my homework first every day.' },
      { hint: '没有规矩，不成方圆。', target: 'No rules, no order.' },
      { hint: '礼貌对待每个人。', target: 'Be polite and treat everyone with respect.' },
    ],
    words: [
      { word: 'rule', phonetic: '/ruːl/', meaning: 'n. 规则；规章' },
      { word: 'order', phonetic: '/ˈɔːdə(r)/', meaning: 'n. 秩序；命令 v. 点菜；命令' },
      { word: 'follow', phonetic: '/ˈfɒləʊ/', meaning: 'v. 遵循；跟随' },
      { word: 'late for', phonetic: '', meaning: '迟到' },
      { word: 'arrive', phonetic: '/əˈraɪv/', meaning: 'v. 到达' },
      { word: 'on time', phonetic: '', meaning: '准时' },
      { word: 'hallway', phonetic: '/ˈhɔːlweɪ/', meaning: 'n. 走廊' },
      { word: 'uniform', phonetic: '/ˈjuːnɪfɔːm/', meaning: 'n. 校服；制服' },
      { word: 'litter', phonetic: '/ˈlɪtə(r)/', meaning: 'v. 乱扔 n. 垃圾' },
      { word: 'polite', phonetic: '/pəˈlaɪt/', meaning: 'adj. 有礼貌的' },
      { word: 'treat', phonetic: '/triːt/', meaning: 'v. 对待；招待；治疗 n. 款待' },
      { word: 'respect', phonetic: '/rɪˈspekt/', meaning: 'n. & v. 尊敬' },
      { word: 'if', phonetic: '/ɪf/', meaning: 'conj. 如果' },
      { word: 'jacket', phonetic: '/ˈdʒækɪt/', meaning: 'n. 夹克衫；短上衣' },
      { word: 'have to', phonetic: '', meaning: '不得不' },
      { word: 'everything', phonetic: '/ˈevriθɪŋ/', meaning: 'pron. 每件事；一切' },
      { word: 'lend', phonetic: '/lend/', meaning: 'v. 借给；借出' },
      { word: 'sweet', phonetic: '/swiːt/', meaning: 'n. 糖果 adj. 甜的' },
      { word: 'snack', phonetic: '/snæk/', meaning: 'n. 点心；小吃' },
      { word: 'of course', phonetic: '', meaning: '当然' },
      { word: 'mobile', phonetic: '/ˈməʊbaɪl/', meaning: 'adj. 可移动的' },
      { word: 'mobile phone', phonetic: '', meaning: '手机' },
      { word: 'turn off', phonetic: '', meaning: '关掉（水、电或煤气）' },
      { word: 'queue', phonetic: '/kjuː/', meaning: 'n. 队' },
      { word: 'jump the queue', phonetic: '', meaning: '插队' },
      { word: 'feed', phonetic: '/fiːd/', meaning: 'v. 喂养；饲养' },
      { word: 'leave', phonetic: '/liːv/', meaning: 'v. 离开；留下' },
      { word: 'absent', phonetic: '/ˈæbsənt/', meaning: 'adj. 缺席的；不在的' },
      { word: 'absent from', phonetic: '', meaning: '缺席；不在' },
      { word: 'shh', phonetic: '/ʃ/', meaning: 'interj. 嘘（用以让别人安静下来）' },
      { word: 'quietly', phonetic: '/ˈkwaɪətli/', meaning: 'adv. 轻声地；安静地' },
      { word: 'belt', phonetic: '/belt/', meaning: 'n. 安全带；腰带；皮带' },
      { word: 'noise', phonetic: '/nɔɪz/', meaning: 'n. 声音；噪声' },
      { word: 'unhappy', phonetic: '/ʌnˈhæpi/', meaning: 'adj. 不快乐的' },
      { word: 'make sb\'s/the bed', phonetic: '', meaning: '整理床铺；铺床' },
      { word: 'either', phonetic: '/ˈaɪðə(r); ˈiːðə(r)/', meaning: 'adv. 也（用于否定词组后）' },
      { word: 'practise', phonetic: '/ˈpræktɪs/', meaning: 'v. 训练；练习' },
      { word: 'hang', phonetic: '/hæŋ/', meaning: 'v. 悬挂' },
      { word: 'hang out', phonetic: '', meaning: '闲逛；常去某处' },
      { word: 'weekday', phonetic: '/ˈwiːkdeɪ/', meaning: 'n. 工作日（星期一至星期五的任何一天）' },
      { word: 'awful', phonetic: '/ˈɔːfl/', meaning: 'adj. 糟糕的；讨厌的' },
      { word: 'become', phonetic: '/bɪˈkʌm/', meaning: 'v. 变成；成为' },
      { word: 'better', phonetic: '/ˈbetə(r)/', meaning: 'adj. 较好的 adv. 较好地' },
      { word: 'person', phonetic: '/ˈpɜːsn/', meaning: 'n. 人' },
      { word: 'focus', phonetic: '/ˈfəʊkəs/', meaning: 'v. 集中（注意力、精力等）；聚焦' },
      { word: 'focus on', phonetic: '', meaning: '集中（注意力、精力等）于' },
      { word: 'build', phonetic: '/bɪld/', meaning: 'v. 创建；建造' },
      { word: 'spirit', phonetic: '/ˈspɪrɪt/', meaning: 'n. 精神；情绪' },
      { word: 'think about', phonetic: '', meaning: '思考；考虑' },
      { word: 'relax', phonetic: '/rɪˈlæks/', meaning: 'v. 放松；休息' },
      { word: 'advice', phonetic: '/ədˈvaɪs/', meaning: 'n. 建议；意见' },
      { word: 'understand', phonetic: '/ˌʌndəˈstænd/', meaning: 'v. 理解；领会' },
      { word: 'untidy', phonetic: '/ʌnˈtaɪdi/', meaning: 'adj. 不整洁的' },
    ]
  },
  {
    id: 'unit-10',
    name: 'Unit 3: Keep Fit (下)',
    desc: '运动锻炼、物主代词、频率副词',
    level: '下册',
    sentences: [
      { hint: '你多久做一次运动？', target: 'How often do you do sport or exercise?' },
      { hint: '我每周打三次乒乓球。', target: 'I play ping-pong three times a week.' },
      { hint: '这个棒球手套是你的吗？', target: 'Is this baseball glove yours?' },
      { hint: '是的，是我的。', target: 'Yes, that is mine.' },
      { hint: '不，不是我的。我想是韩林的。', target: 'No, that is not mine. I think it is Han Lin\'s.' },
      { hint: '他的上面有 HL 两个字母。', target: 'His has HL on it.' },
      { hint: '你经常打乒乓球吗？', target: 'Do you often play ping-pong?' },
      { hint: '我几乎不踢足球。', target: 'I hardly ever play football.' },
      { hint: '我的网球拍在哪里？', target: 'Where is my tennis racket?' },
      { hint: '你的在这儿。', target: 'Yours is right here.' },
      { hint: '这些是我们的棒球吗？', target: 'Are these our baseballs?' },
      { hint: '不，它们是艾玛和艾拉的。', target: 'No, they are Emma and Ella\'s.' },
      { hint: '熟能生巧。', target: 'Practice makes perfect.' },
      { hint: '我很少打羽毛球。', target: 'I seldom play badminton.' },
      { hint: '我们应该什么时候一起打双打？', target: 'We should all play doubles sometime!' },
    ],
    words: [
      { word: 'fit', phonetic: '/fɪt/', meaning: 'adj. 健康的；健壮的 v. 适合' },
      { word: 'baseball', phonetic: '/ˈbeɪsbɔːl/', meaning: 'n. 棒球（运动）' },
      { word: 'glove', phonetic: '/ɡlʌv/', meaning: 'n. （手指分开的）手套' },
      { word: 'mat', phonetic: '/mæt/', meaning: 'n. （运动用的）垫子' },
      { word: 'rope', phonetic: '/rəʊp/', meaning: 'n. 绳子；粗绳' },
      { word: 'jump rope', phonetic: '', meaning: '跳绳用的绳子；跳绳（运动）' },
      { word: 'racket', phonetic: '/ˈrækɪt/', meaning: 'n. （网球、羽毛球等的）球拍' },
      { word: 'hardly', phonetic: '/ˈhɑːdli/', meaning: 'adv. 几乎不；几乎没有' },
      { word: 'ever', phonetic: '/ˈevə(r)/', meaning: 'adv. 在任何时候；从来；曾经' },
      { word: 'hardly ever', phonetic: '', meaning: '几乎从不' },
      { word: 'once', phonetic: '/wʌns/', meaning: 'adv. 一次；曾经 conj. 一旦' },
      { word: 'twice', phonetic: '/twaɪs/', meaning: 'adv. 两次；两倍' },
      { word: 'mine', phonetic: '/maɪn/', meaning: 'pron. 我的（所有物）' },
      { word: 'hers', phonetic: '/hɜːz; ɜːz/', meaning: 'pron. 她的（所有物）' },
      { word: 'maybe', phonetic: '/ˈmeɪbi/', meaning: 'adv. 也许；大概' },
      { word: 'well-used', phonetic: '/ˌwelˈjuːzd/', meaning: 'adj. 使用得多的' },
      { word: 'practice', phonetic: '/ˈpræktɪs/', meaning: 'n. 练习；实践' },
      { word: 'perfect', phonetic: '/ˈpɜːfɪkt/', meaning: 'adj. 完美的；极好的' },
      { word: 'seldom', phonetic: '/ˈseldəm/', meaning: 'adv. 很少；不常' },
      { word: 'badminton', phonetic: '/ˈbædmɪntən/', meaning: 'n. 羽毛球运动' },
      { word: 'double', phonetic: '/ˈdʌbl/', meaning: 'n. 双打（doubles）；两倍 adj. 成双的；两倍的' },
      { word: 'sometime', phonetic: '/ˈsʌmtaɪm/', meaning: 'adv. 在某个时候' },
      { word: 'volleyball', phonetic: '/ˈvɒlibɔːl/', meaning: 'n. 排球（运动）' },
      { word: 'theirs', phonetic: '/ðeəz/', meaning: 'pron. 他们的，她们的，它们的（所有物）' },
      { word: 'jog', phonetic: '/dʒɒɡ/', meaning: 'v. 慢跑' },
      { word: 'few', phonetic: '/fjuː/', meaning: 'adj. （表示否定的）很少的；几乎没有的' },
      { word: 'a few', phonetic: '', meaning: '少数；几个' },
      { word: 'excuse', phonetic: '/ɪkˈskjuːz/', meaning: 'v. 原谅；宽恕' },
      { word: 'excuse me', phonetic: '', meaning: '劳驾；请原谅' },
      { word: 'over there', phonetic: '', meaning: '在那边' },
      { word: 'just', phonetic: '/dʒʌst/', meaning: 'adv. 只是；正好' },
      { word: 'T-shirt', phonetic: '/ˈtiː ʃɜːt/', meaning: 'n. T恤衫' },
      { word: 'belong', phonetic: '/bɪˈlɒŋ/', meaning: 'v. 应在（某处）' },
      { word: 'belong to', phonetic: '', meaning: '属于（某人）' },
      { word: 'working', phonetic: '/ˈwɜːkɪŋ/', meaning: 'adj. 工作的' },
      { word: 'working day', phonetic: '', meaning: '工作日' },
      { word: 'full of', phonetic: '', meaning: '有许多；充满' },
      { word: 'energy', phonetic: '/ˈenədʒi/', meaning: 'n. 精力；能量' },
      { word: 'group', phonetic: '/ɡruːp/', meaning: 'n. 组；群' },
      { word: 'skateboard', phonetic: '/ˈskeɪtbɔːd/', meaning: 'n. 滑板' },
      { word: 'encourage', phonetic: '/ɪnˈkʌrɪdʒ/', meaning: 'v. 鼓励；激励' },
      { word: 'trick', phonetic: '/trɪk/', meaning: 'n. 技巧；戏法' },
      { word: 'succeed', phonetic: '/səkˈsiːd/', meaning: 'v. 成功；达到目标' },
      { word: 'skateboarding', phonetic: '/ˈskeɪtbɔːdɪŋ/', meaning: 'n. 滑板运动' },
      { word: 'goal', phonetic: '/ɡəʊl/', meaning: 'n. 目标；目的' },
      { word: 'sit-up', phonetic: '/ˈsɪtʌp/', meaning: 'n. 仰卧起坐' },
      { word: 'work out', phonetic: '', meaning: '锻炼' },
      { word: 'app', phonetic: '/æp/', meaning: 'n. 应用程序' },
      { word: 'progress', phonetic: '/ˈprəʊɡres/', meaning: 'n. 进步；进展' },
      { word: 'match', phonetic: '/mætʃ/', meaning: 'n. 比赛；竞赛' },
      { word: 'team', phonetic: '/tiːm/', meaning: 'n. 队；组' },
      { word: 'ours', phonetic: '/ˈaʊəz; ɑːz/', meaning: 'pron. 我们的（所有物）' },
      { word: 'lose', phonetic: '/luːz/', meaning: 'v. 输掉；丢失' },
      { word: 'teenager', phonetic: '/ˈtiːneɪdʒə(r)/', meaning: 'n. 青少年（13岁至19岁之间）' },
    ]
  },
  {
    id: 'unit-11',
    name: 'Unit 4: Eat Well (下)',
    desc: '饮食、可数/不可数名词、选择疑问句',
    level: '下册',
    sentences: [
      { hint: '你早餐通常吃什么？', target: 'What do you usually have for breakfast?' },
      { hint: '我通常喝牛奶吃面包。', target: 'I usually have milk and bread.' },
      { hint: '你想要茶还是咖啡？', target: 'Would you like tea or coffee?' },
      { hint: '请给我一些茶。', target: 'I would like some tea, please.' },
      { hint: '你午饭想吃什么？', target: 'What would you like for lunch?' },
      { hint: '你想要多少个苹果？', target: 'How many apples would you like?' },
      { hint: '请给我两个苹果。', target: 'I would like two apples, please.' },
      { hint: '你想要多少牛奶？', target: 'How much milk would you like?' },
      { hint: '我喜欢健康饮食。', target: 'I like to eat well.' },
      { hint: '太多糖对你不好。', target: 'Too much sugar is not good for you.' },
      { hint: '你更喜欢哪种食物，中式还是西式？', target: 'Which do you prefer, Chinese food or Western food?' },
      { hint: '我们每天应该多吃水果和蔬菜。', target: 'We should eat more fruit and vegetables every day.' },
      { hint: '你的饮食习惯是什么？', target: 'What are your eating habits?' },
      { hint: '我们需要做出健康的选择。', target: 'We need to make healthy eating choices.' },
      { hint: '我喜欢吃鸡肉和米饭。', target: 'I like to eat chicken and rice.' },
    ],
    words: [
      { word: 'watermelon', phonetic: '/ˈwɔːtəˌmelən/', meaning: 'n. 西瓜' },
      { word: 'cabbage', phonetic: '/ˈkæbɪdʒ/', meaning: 'n. 卷心菜' },
      { word: 'mutton', phonetic: '/ˈmʌtn/', meaning: 'n. 羊肉' },
      { word: 'cookie', phonetic: '/ˈkʊki/', meaning: 'n. 曲奇饼' },
      { word: 'onion', phonetic: '/ˈʌnjən/', meaning: 'n. 洋葱；葱头' },
      { word: 'dumpling', phonetic: '/ˈdʌmplɪŋ/', meaning: 'n. 饺子' },
      { word: 'coffee', phonetic: '/ˈkɒfi/', meaning: 'n. 咖啡' },
      { word: 'bean', phonetic: '/biːn/', meaning: 'n. 豆' },
      { word: 'chip', phonetic: '/tʃɪp/', meaning: 'n. 炸薯条' },
      { word: 'fish and chips', phonetic: '', meaning: '炸鱼薯条' },
      { word: 'salad', phonetic: '/ˈsæləd/', meaning: 'n. 沙拉；色拉' },
      { word: 'porridge', phonetic: '/ˈpɒrɪdʒ/', meaning: 'n. 粥；麦片粥' },
      { word: 'waiter', phonetic: '/ˈweɪtə(r)/', meaning: 'n. （男）服务员' },
      { word: 'What about …?', phonetic: '', meaning: '……怎么样？' },
      { word: 'taste', phonetic: '/teɪst/', meaning: 'v. 有……味道；尝 n. 味道' },
      { word: 'anything', phonetic: '/ˈeniθɪŋ/', meaning: 'pron. 某事物；任何事物' },
      { word: 'dish', phonetic: '/dɪʃ/', meaning: 'n. 一道菜；盘子' },
      { word: 'choice', phonetic: '/tʃɔɪs/', meaning: 'n. 选择' },
      { word: 'meal', phonetic: '/miːl/', meaning: 'n. 一餐所吃的食物；一餐' },
      { word: 'pork', phonetic: '/pɔːk/', meaning: 'n. 猪肉' },
      { word: 'strawberry', phonetic: '/ˈstrɔːbəri/', meaning: 'n. 草莓' },
      { word: 'menu', phonetic: '/ˈmenjuː/', meaning: 'n. 菜单' },
      { word: 'customer', phonetic: '/ˈkʌstəmə(r)/', meaning: 'n. 顾客' },
      { word: 'serve', phonetic: '/sɜːv/', meaning: 'v. 提供；服务' },
      { word: 'waitress', phonetic: '/ˈweɪtrəs/', meaning: 'n. 女服务员' },
      { word: 'sir', phonetic: '/sɜː(r)/', meaning: 'n. 先生' },
      { word: 'go with', phonetic: '', meaning: '搭配；相配' },
      { word: 'instead', phonetic: '/ɪnˈsted/', meaning: 'adv. 反而；代替' },
      { word: 'pear', phonetic: '/peə(r)/', meaning: 'n. 梨' },
      { word: 'too much', phonetic: '', meaning: '太多' },
      { word: 'sugar', phonetic: '/ˈʃʊɡə(r)/', meaning: 'n. 糖' },
      { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: 'v. 改进；改善' },
      { word: 'habit', phonetic: '/ˈhæbɪt/', meaning: 'n. 习惯' },
      { word: 'fast food', phonetic: '', meaning: '快餐' },
      { word: 'salt', phonetic: '/sɔːlt; sɒlt/', meaning: 'n. 盐' },
      { word: 'fat', phonetic: '/fæt/', meaning: 'n. 脂肪 adj. 肥胖的' },
      { word: 'put on', phonetic: '', meaning: '增加；穿上' },
      { word: 'weight', phonetic: '/weɪt/', meaning: 'n. 体重；重量' },
      { word: 'hamburger', phonetic: '/ˈhæmbɜːɡə(r)/', meaning: 'n. 汉堡包' },
      { word: 'cause', phonetic: '/kɔːz/', meaning: 'v. 造成；导致' },
      { word: 'heart', phonetic: '/hɑːt/', meaning: 'n. 心脏；中心' },
      { word: 'balanced', phonetic: '/ˈbælənst/', meaning: 'adj. 均衡的；平衡的' },
      { word: 'too … to', phonetic: '', meaning: '太……以至于不能' },
      { word: 'sleepy', phonetic: '/ˈsliːpi/', meaning: 'adj. 困倦的；想睡的' },
      { word: 'after all', phonetic: '', meaning: '毕竟；终归' },
      { word: 'away', phonetic: '/əˈweɪ/', meaning: 'adv. 离开；在别处' },
      { word: 'poor', phonetic: '/pɔː(r); pʊə(r)/', meaning: 'adj. 不好的；贫穷的；可怜的' },
      { word: 'result', phonetic: '/rɪˈzʌlt/', meaning: 'n. 后果；结果' },
      { word: 'article', phonetic: '/ˈɑːtɪkl/', meaning: 'n. 文章；冠词' },
      { word: 'common', phonetic: '/ˈkɒmən/', meaning: 'adj. 共同的；普遍的' },
      { word: 'among', phonetic: '/əˈmʌŋ/', meaning: 'prep. 在……中；……之一' },
      { word: 'soft', phonetic: '/sɒft/', meaning: 'adj. 柔和的；柔软的' },
      { word: 'soft drink', phonetic: '', meaning: '软饮料（不含酒精）' },
      { word: 'enough', phonetic: '/ɪˈnʌf/', meaning: 'adj. 足够的 adv. 足够地 pron. 足够' },
      { word: 'thirsty', phonetic: '/ˈθɜːsti/', meaning: 'adj. 渴的' },
    ]
  },
  {
    id: 'unit-12',
    name: 'Unit 5: Here and Now (下)',
    desc: '现在进行时、描述正在发生的事',
    level: '下册',
    sentences: [
      { hint: '你现在在做什么？', target: 'What are you doing right now?' },
      { hint: '我正在做作业。', target: 'I am doing my homework.' },
      { hint: '他们正在操场上跑步。', target: 'They are running on the playground.' },
      { hint: '你正在和谁说话？', target: 'Who are you talking to?' },
      { hint: '她正在听音乐。', target: 'She is listening to music.' },
      { hint: '他正在看书。', target: 'He is reading a book.' },
      { hint: '外面正在下雨。', target: 'It is raining outside.' },
      { hint: '世界各地的人正在做什么？', target: 'What are people around the world doing?' },
      { hint: '一些人在睡觉，一些人在工作。', target: 'Some people are sleeping, and some are working.' },
      { hint: '我们在等公共汽车。', target: 'We are waiting for the bus.' },
      { hint: '他们正在上英语课。', target: 'They are having an English class.' },
      { hint: '妈妈正在厨房做饭。', target: 'Mum is cooking in the kitchen.' },
      { hint: '孩子们正在公园里玩。', target: 'The children are playing in the park.' },
      { hint: '别打扰他，他正在学习。', target: 'Do not disturb him. He is studying.' },
      { hint: '你正在找什么？', target: 'What are you looking for?' },
    ],
    words: [
      { word: 'right now', phonetic: '', meaning: '现在；立刻' },
      { word: 'ride', phonetic: '/raɪd/', meaning: 'v. 骑 n. 旅程' },
      { word: 'moment', phonetic: '/ˈməʊmənt/', meaning: 'n. 某个时刻；片刻；瞬间' },
      { word: 'at the moment', phonetic: '', meaning: '现在；此刻' },
      { word: 'work on', phonetic: '', meaning: '做；从事' },
      { word: 'dragon', phonetic: '/ˈdræɡən/', meaning: 'n. 龙' },
      { word: 'festival', phonetic: '/ˈfestɪvl/', meaning: 'n. 节日' },
      { word: 'hold', phonetic: '/həʊld/', meaning: 'v. 拿着；抓住' },
      { word: 'hold on', phonetic: '', meaning: '别挂断电话；等一等' },
      { word: 'voice', phonetic: '/vɔɪs/', meaning: 'n. 嗓音；声音' },
      { word: 'race', phonetic: '/reɪs/', meaning: 'n. 比赛；竞赛' },
      { word: 'darling', phonetic: '/ˈdɑːlɪŋ/', meaning: 'n. 亲爱的；宝贝' },
      { word: 'somebody', phonetic: '/ˈsʌmbədi/', meaning: 'pron. 某人；有人' },
      { word: 'could', phonetic: '/kʊd; kəd/', meaning: 'modal v. 能；可以' },
      { word: 'message', phonetic: '/ˈmesɪdʒ/', meaning: 'n. 消息；信息' },
      { word: 'take a message', phonetic: '', meaning: '捎个口信' },
      { word: 'leave a message', phonetic: '', meaning: '留个口信' },
      { word: 'call back', phonetic: '', meaning: '回电话' },
      { word: 'kick', phonetic: '/kɪk/', meaning: 'v. 踢；踹' },
      { word: 'wow', phonetic: '/waʊ/', meaning: 'interj. 哇；呀' },
      { word: 'online', phonetic: '/ˌɒnˈlaɪn/', meaning: 'adj. 在线的' },
      { word: 'shuttlecock', phonetic: '/ˈʃʌtlkɒk/', meaning: 'n. 羽毛球' },
      { word: 'sight', phonetic: '/saɪt/', meaning: 'n. 名胜；风景；视力' },
      { word: 'exam', phonetic: '/ɪɡˈzæm/', meaning: 'n. 考试' },
      { word: 'hope', phonetic: '/həʊp/', meaning: 'v. & n. 希望' },
      { word: 'forward', phonetic: '/ˈfɔːwəd/', meaning: 'adv. 向前' },
      { word: 'look forward to', phonetic: '', meaning: '盼望' },
      { word: 'skate', phonetic: '/skeɪt/', meaning: 'v. 滑冰' },
      { word: 'happen', phonetic: '/ˈhæpən/', meaning: 'v. 发生' },
      { word: 'zone', phonetic: '/zəʊn/', meaning: 'n. 地区；地带；区域' },
      { word: 'time zone', phonetic: '', meaning: '时区' },
      { word: 'around the world', phonetic: '', meaning: '世界各地' },
      { word: 'rush', phonetic: '/rʌʃ/', meaning: 'v. & n. 冲；奔' },
      { word: 'in a hurry', phonetic: '', meaning: '匆忙' },
      { word: 'shine', phonetic: '/ʃaɪn/', meaning: 'v. 发光；照耀 n. 光亮' },
      { word: 'brightly', phonetic: '/ˈbraɪtli/', meaning: 'adv. 明亮地' },
      { word: 'colourful', phonetic: '/ˈkʌləfl/', meaning: 'adj. 色彩鲜艳的' },
      { word: 'slowly', phonetic: '/ˈsləʊli/', meaning: 'adv. 缓慢地' },
      { word: 'such', phonetic: '/sʌtʃ/', meaning: 'adj. 这样的；那样的 pron. 这样（那样）的人或事物' },
      { word: 'such as', phonetic: '', meaning: '例如' },
      { word: 'painting', phonetic: '/ˈpeɪntɪŋ/', meaning: 'n. 绘画作品；绘画；油画' },
      { word: 'market', phonetic: '/ˈmɑːkɪt/', meaning: 'n. 市场' },
      { word: 'side', phonetic: '/saɪd/', meaning: 'n. 边；侧' },
      { word: 'side by side', phonetic: '', meaning: '并排；并肩地' },
      { word: 'subway', phonetic: '/ˈsʌbweɪ/', meaning: 'n. 地铁' },
      { word: 'bright', phonetic: '/braɪt/', meaning: 'adj. 鲜艳的；明亮的；聪明的' },
      { word: 'drop', phonetic: '/drɒp/', meaning: 'v. 把……送至；落下 n. 滴；下降' },
      { word: 'drop off', phonetic: '', meaning: '（开车）把某人送到某处' },
      { word: 'passenger', phonetic: '/ˈpæsɪndʒə(r)/', meaning: 'n. 乘客' },
      { word: 'central', phonetic: '/ˈsentrəl/', meaning: 'adj. 中心的；中央的' },
      { word: 'explain', phonetic: '/ɪkˈspleɪn/', meaning: 'v. 解释；说明' },
      { word: 'take part in', phonetic: '', meaning: '参加' },
      { word: 'tour', phonetic: '/tʊə(r)/', meaning: 'n. & v. 旅行；旅游' },
      { word: 'sunshine', phonetic: '/ˈsʌnʃaɪn/', meaning: 'n. 阳光' },
      { word: 'drive', phonetic: '/draɪv/', meaning: 'v. 开车；驾驶' },
      { word: 'rush hour', phonetic: '', meaning: '（上下班时的）交通高峰期' },
    ]
  },
  {
    id: 'unit-13',
    name: 'Unit 6: Rain or Shine (下)',
    desc: '天气描述、天气与活动',
    level: '下册',
    sentences: [
      { hint: '今天天气怎么样？', target: 'What is the weather like today?' },
      { hint: '今天天气晴朗。', target: 'It is sunny today.' },
      { hint: '明天会下雨吗？', target: 'Will it rain tomorrow?' },
      { hint: '外面正在下雪。', target: 'It is snowing outside.' },
      { hint: '今天风很大。', target: 'It is very windy today.' },
      { hint: '天气炎热，我想去游泳。', target: 'It is hot. I want to go swimming.' },
      { hint: '天气寒冷，多穿点衣服。', target: 'It is cold. Wear more clothes.' },
      { hint: '春天天气温暖。', target: 'The weather is warm in spring.' },
      { hint: '天气如何影响我们？', target: 'How does the weather affect us?' },
      { hint: '我不喜欢雨天因为我不能出去玩。', target: 'I do not like rainy days because I cannot go out to play.' },
      { hint: '我喜欢晴天因为我可以去公园。', target: 'I like sunny days because I can go to the park.' },
      { hint: '今天温度是多少度？', target: 'What is the temperature today?' },
      { hint: '今天最高温度三十度。', target: 'The highest temperature today is thirty degrees.' },
      { hint: '多云的天气很凉爽。', target: 'Cloudy weather is cool.' },
      { hint: '你更喜欢什么天气？', target: 'What weather do you prefer?' },
    ],
    words: [
      { word: 'rain or shine', phonetic: '', meaning: '不论是雨或是晴；不管发生什么事' },
      { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响' },
      { word: 'dry', phonetic: '/draɪ/', meaning: 'adj. 干的；干旱的' },
      { word: 'lightning', phonetic: '/ˈlaɪtnɪŋ/', meaning: 'n. 闪电' },
      { word: 'stormy', phonetic: '/ˈstɔːmi/', meaning: 'adj. 有暴风雨（或暴风雪）的' },
      { word: 'north', phonetic: '/nɔːθ/', meaning: 'n. 北部；北；北方' },
      { word: 'west', phonetic: '/west/', meaning: 'n. 西部；西；西方' },
      { word: 'south', phonetic: '/saʊθ/', meaning: 'n. 南部；南；南方' },
      { word: 'east', phonetic: '/iːst/', meaning: 'n. 东部；东；东方' },
      { word: 'stay in', phonetic: '', meaning: '待在家里；没有外出' },
      { word: 'lucky', phonetic: '/ˈlʌki/', meaning: 'adj. 运气好的；带来好运的' },
      { word: 'lucky you', phonetic: '', meaning: '你真幸运' },
      { word: 'sunbathe', phonetic: '/ˈsʌnbeɪð/', meaning: 'v. 沐日光浴；晒太阳' },
      { word: 'some day', phonetic: '', meaning: '将来；有朝一日' },
      { word: 'temperature', phonetic: '/ˈtemprətʃə(r)/', meaning: 'n. 温度' },
      { word: 'snowman', phonetic: '/ˈsnəʊmæn/', meaning: 'n. (pl. snowmen) 雪人' },
      { word: 'heavily', phonetic: '/ˈhevɪli/', meaning: 'adv. 大量地；沉重地' },
      { word: 'snowy', phonetic: '/ˈsnəʊi/', meaning: 'adj. 下雪的；雪白的' },
      { word: 'beach volleyball', phonetic: '', meaning: '沙滩排球' },
      { word: 'high', phonetic: '/haɪ/', meaning: 'adv. & adj. 高' },
      { word: 'freezing', phonetic: '/ˈfriːzɪŋ/', meaning: 'adj. 极冷的；冰冻的' },
      { word: 'tourist', phonetic: '/ˈtʊərɪst/', meaning: 'n. 旅行者；观光客' },
      { word: 'mount', phonetic: '/maʊnt/', meaning: 'n. 山；山峰' },
      { word: 'cloud', phonetic: '/klaʊd/', meaning: 'n. 云；云彩' },
      { word: 'feel like', phonetic: '', meaning: '感觉像' },
      { word: 'magical', phonetic: '/ˈmædʒɪkl/', meaning: 'adj. 魔法的；神奇的' },
      { word: 'rock', phonetic: '/rɒk/', meaning: 'n. 岩石' },
      { word: 'rest', phonetic: '/rest/', meaning: 'n. 休息；剩余部分' },
      { word: 'area', phonetic: '/ˈeəriə/', meaning: 'n. 场地；地区' },
      { word: 'rest area', phonetic: '', meaning: '休息区' },
      { word: 'make progress', phonetic: '', meaning: '取得进展' },
      { word: 'although', phonetic: '/ɔːlˈðəʊ/', meaning: 'conj. 虽然；尽管' },
      { word: 'still', phonetic: '/stɪl/', meaning: 'adv. 还；仍然' },
      { word: 'in high spirits', phonetic: '', meaning: '情绪高涨；兴高采烈' },
      { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning: 'n. 经历；经验 v. 经历' },
      { word: 'through', phonetic: '/θruː/', meaning: 'prep. 穿过；凭借' },
      { word: 'glad', phonetic: '/ɡlæd/', meaning: 'adj. 高兴的' },
      { word: 'peak', phonetic: '/piːk/', meaning: 'n. 山顶；顶点' },
      { word: 'grey', phonetic: '/ɡreɪ/', meaning: 'adj. 灰色的' },
      { word: 'because of', phonetic: '', meaning: '因为' },
      { word: 'fog', phonetic: '/fɒɡ/', meaning: 'n. 雾' },
      { word: 'ground', phonetic: '/ɡraʊnd/', meaning: 'n. 地面' },
      { word: 'wet', phonetic: '/wet/', meaning: 'adj. 湿的' },
      { word: 'tiring', phonetic: '/ˈtaɪərɪŋ/', meaning: 'adj. 令人疲倦的；累人的' },
      { word: 'seem', phonetic: '/siːm/', meaning: 'v. 似乎；好像' },
      { word: 'sunlight', phonetic: '/ˈsʌnlaɪt/', meaning: 'n. 阳光；日光' },
      { word: 'at the top', phonetic: '', meaning: '在顶部；在顶端' },
      { word: 'thought', phonetic: '/θɔːt/', meaning: 'n. 想法' },
      { word: 'mountain', phonetic: '/ˈmaʊntən/', meaning: 'n. 山；高山' },
      { word: 'at the start', phonetic: '', meaning: '开始；起初' },
      { word: 'end', phonetic: '/end/', meaning: 'n. 末尾；结束' },
      { word: 'at the end', phonetic: '', meaning: '最后；在末尾' },
      { word: 'storm', phonetic: '/stɔːm/', meaning: 'n. 暴风雨；暴风雪' },
      { word: 'pour', phonetic: '/pɔː(r)/', meaning: 'v. 倾倒；倒出' },
      { word: 'wind', phonetic: '/wɪnd/', meaning: 'n. 风' },
      { word: 'shout', phonetic: '/ʃaʊt/', meaning: 'v. & n. 喊叫；呼唤' },
      { word: 'run after', phonetic: '', meaning: '追逐' },
    ]
  },
  {
    id: 'unit-14',
    name: 'Unit 7: A Day to Remember (下)',
    desc: '一般过去时、难忘的一天',
    level: '下册',
    sentences: [
      { hint: '你昨天做了什么？', target: 'What did you do yesterday?' },
      { hint: '我昨天参观了一个农场。', target: 'I visited a farm yesterday.' },
      { hint: '我们上周去了学校旅行。', target: 'We went on a school trip last week.' },
      { hint: '那天非常有趣。', target: 'That was a lot of fun.' },
      { hint: '你学到了什么？', target: 'What did you learn?' },
      { hint: '我学会了种菜。', target: 'I learned how to grow vegetables.' },
      { hint: '他们昨天爬了黄山。', target: 'They climbed Mount Huangshan yesterday.' },
      { hint: '那天天气很好。', target: 'The weather was great that day.' },
      { hint: '我拍了很多照片。', target: 'I took many photos.' },
      { hint: '那是什么特别的一天！', target: 'What a special day that was!' },
      { hint: '你什么时候到那儿的？', target: 'When did you get there?' },
      { hint: '我们早上八点到的。', target: 'We got there at eight in the morning.' },
      { hint: '我们玩得很开心。', target: 'We had a great time.' },
      { hint: '那是一个难忘的日子。', target: 'It was a day to remember.' },
      { hint: '我昨天帮妈妈做了家务。', target: 'I helped my mum do housework yesterday.' },
    ],
    words: [
      { word: 'meet up', phonetic: '', meaning: '碰头；相聚' },
      { word: 'museum', phonetic: '/mjuˈziːəm/', meaning: 'n. 博物馆' },
      { word: 'exhibition', phonetic: '/ˌeksɪˈbɪʃn/', meaning: 'n. 展览' },
      { word: 'direction', phonetic: '/dɪˈrekʃn; daɪˈrekʃn/', meaning: 'n. 方向' },
      { word: 'trip', phonetic: '/trɪp/', meaning: 'n. 旅行' },
      { word: 'wastewater', phonetic: '/ˈweɪstwɔːtə(r)/', meaning: 'n. 废水' },
      { word: 'plant', phonetic: '/plɑːnt/', meaning: 'n. 工厂' },
      { word: 'into', phonetic: '/ˈɪntuː; ˈɪntə/', meaning: 'prep. 到……里面；进入' },
      { word: 'remove', phonetic: '/rɪˈmuːv/', meaning: 'v. 移开；拿走' },
      { word: 'piece', phonetic: '/piːs/', meaning: 'n. 片；块' },
      { word: 'waste', phonetic: '/weɪst/', meaning: 'n. 废弃物 v. 浪费' },
      { word: 'machine', phonetic: '/məˈʃiːn/', meaning: 'n. 机器' },
      { word: 'germ', phonetic: '/dʒɜːm/', meaning: 'n. 微生物；细菌' },
      { word: 'step', phonetic: '/step/', meaning: 'n. 步骤；脚步' },
      { word: 'used to', phonetic: '', meaning: '过去常常（做）' },
      { word: 'realize', phonetic: '/ˈrɪəlaɪz/', meaning: 'v. 认识到；实现' },
      { word: 'inside', phonetic: '/ˌɪnˈsaɪd/', meaning: 'prep. 在……里面 adv. 在里面' },
      { word: 'go on a trip', phonetic: '', meaning: '去旅行' },
      { word: 'process', phonetic: '/ˈprəʊses/', meaning: 'n. 过程' },
      { word: 'theatre', phonetic: '/ˈθɪətə(r)/', meaning: 'n. 戏院；剧场；电影院' },
      { word: 'factory', phonetic: '/ˈfæktri; ˈfæktəri/', meaning: 'n. 工厂' },
      { word: 'terrible', phonetic: '/ˈterəbl/', meaning: 'adj. 糟糕的' },
      { word: 'actor', phonetic: '/ˈæktə(r)/', meaning: 'n. 演员' },
      { word: 'gun', phonetic: '/ɡʌn/', meaning: 'n. 枪' },
      { word: 'try on', phonetic: '', meaning: '试穿' },
      { word: 'along', phonetic: '/əˈlɒŋ/', meaning: 'prep. 沿着；顺着' },
      { word: 'road', phonetic: '/rəʊd/', meaning: 'n. 道路' },
      { word: 'create', phonetic: '/kriˈeɪt/', meaning: 'v. 创造' },
      { word: 'record', phonetic: '/rɪˈkɔːd/', meaning: 'v. 记录 n. 记录' },
      { word: 'skill', phonetic: '/skɪl/', meaning: 'n. 技能' },
      { word: 'write down', phonetic: '', meaning: '写下；记下' },
      { word: 'explore', phonetic: '/ɪkˈsplɔː(r)/', meaning: 'v. 探索' },
      { word: 'tent', phonetic: '/tent/', meaning: 'n. 帐篷' },
      { word: 'cucumber', phonetic: '/ˈkjuːkʌmbə(r)/', meaning: 'n. 黄瓜' },
      { word: 'from … to …', phonetic: '', meaning: '从……到……' },
      { word: 'straight', phonetic: '/streɪt/', meaning: 'adv. 直接；立即；笔直地 adj. 直的' },
      { word: 'fill', phonetic: '/fɪl/', meaning: 'v. 装满；盛满' },
      { word: 'basket', phonetic: '/ˈbɑːskɪt/', meaning: 'n. 篮子；筐' },
      { word: 'teach', phonetic: '/tiːtʃ/', meaning: 'v. (taught /tɔːt/) 教' },
      { word: 'branch', phonetic: '/brɑːntʃ/', meaning: 'n. 分支；树枝' },
      { word: 'leaf', phonetic: '/liːf/', meaning: 'n. (pl. leaves /liːvz/) 叶；叶子' },
      { word: 'finally', phonetic: '/ˈfaɪnəli/', meaning: 'adv. 终于' },
      { word: 'think of', phonetic: '', meaning: '考虑；想起' },
      { word: 'grain', phonetic: '/ɡreɪn/', meaning: 'n. 谷物；谷粒' },
      { word: 'fresh', phonetic: '/freʃ/', meaning: 'adj. 新鲜的' },
      { word: 'certainly', phonetic: '/ˈsɜːtnli/', meaning: 'adv. 肯定地' },
      { word: 'diary', phonetic: '/ˈdaɪəri/', meaning: 'n. 日记；日记本' },
      { word: 'entry', phonetic: '/ˈentri/', meaning: 'n. （日记的）一则；入口' },
      { word: 'agree', phonetic: '/əˈɡriː/', meaning: 'v. 赞成；同意' },
      { word: 'agree with', phonetic: '', meaning: '赞成；同意' },
    ]
  },
  {
    id: 'unit-15',
    name: 'Unit 8: Once upon a Time (下)',
    desc: '故事、一般过去时、寓言',
    level: '下册',
    sentences: [
      { hint: '你最喜欢的故事是什么？', target: 'What are your favourite stories?' },
      { hint: '从前有一只丑小鸭。', target: 'Once upon a time, there was an ugly duckling.' },
      { hint: '它和其他鸭子看起来不一样。', target: 'It looked different from the other ducks.' },
      { hint: '没有人喜欢它。', target: 'Nobody liked it.' },
      { hint: '它感到非常孤独。', target: 'It felt very lonely.' },
      { hint: '有一天它变成了一只美丽的天鹅。', target: 'One day it became a beautiful swan.' },
      { hint: '这个故事教会了我们什么？', target: 'What can this story teach us?' },
      { hint: '不要以貌取人。', target: 'Do not judge a book by its cover.' },
      { hint: '从前有一个老人。', target: 'Once upon a time, there was an old man.' },
      { hint: '从前有一只聪明的狐狸。', target: 'Once upon a time, there was a clever fox.' },
      { hint: '狐狸骗了乌鸦。', target: 'The fox tricked the crow.' },
      { hint: '狼来了！', target: 'The wolf is coming!' },
      { hint: '没有人相信那个男孩。', target: 'Nobody believed the boy.' },
      { hint: '诚实是很重要的。', target: 'Being honest is very important.' },
      { hint: '你能给我讲一个故事吗？', target: 'Can you tell me a story?' },
    ],
    words: [
      { word: 'upon', phonetic: '/əˈpɒn/', meaning: 'prep. 在……上' },
      { word: 'once upon a time', phonetic: '', meaning: '从前；很久以前' },
      { word: 'bite', phonetic: '/baɪt/', meaning: 'v. (bit /bɪt/) 咬；咬伤' },
      { word: 'bite through', phonetic: '', meaning: '咬穿' },
      { word: 'net', phonetic: '/net/', meaning: 'n. 网；网状物' },
      { word: 'hunter', phonetic: '/ˈhʌntə(r)/', meaning: 'n. 猎人；搜寻者' },
      { word: 'promise', phonetic: '/ˈprɒmɪs/', meaning: 'v. 承诺；保证 n. 承诺；诺言' },
      { word: 'long ago', phonetic: '', meaning: '很久以前' },
      { word: 'war', phonetic: '/wɔː(r)/', meaning: 'n. 战争' },
      { word: 'neighbour', phonetic: '/ˈneɪbə(r)/', meaning: 'n. 邻居' },
      { word: 'wise', phonetic: '/waɪz/', meaning: 'adj. 明智的；高明的' },
      { word: 'emperor', phonetic: '/ˈempərə(r)/', meaning: 'n. 皇帝' },
      { word: 'lie', phonetic: '/laɪ/', meaning: 'v. 撒谎 n. 谎言' },
      { word: 'pretend', phonetic: '/prɪˈtend/', meaning: 'v. 假装；伪装' },
      { word: 'official', phonetic: '/əˈfɪʃl/', meaning: 'n. 官员；高级职员' },
      { word: 'silly', phonetic: '/ˈsɪli/', meaning: 'adj. 愚蠢的；傻的' },
      { word: 'decide', phonetic: '/dɪˈsaɪd/', meaning: 'v. 决定' },
      { word: 'praise', phonetic: '/preɪz/', meaning: 'v. & n. 赞美；表扬' },
      { word: 'afraid', phonetic: '/əˈfreɪd/', meaning: 'adj. 害怕的；担心的' },
      { word: 'suddenly', phonetic: '/ˈsʌdənli/', meaning: 'adv. 突然地；出乎意料地' },
      { word: 'at first', phonetic: '', meaning: '起初；最初' },
      { word: 'truth', phonetic: '/truːθ/', meaning: 'n. 真相；事实' },
      { word: 'tell the truth', phonetic: '', meaning: '说实话' },
      { word: 'make money', phonetic: '', meaning: '赚钱' },
      { word: 'true', phonetic: '/truː/', meaning: 'adj. 符合事实的；真正的' },
      { word: 'hate', phonetic: '/heɪt/', meaning: 'v. 不喜欢；厌恶；讨厌' },
      { word: 'get out', phonetic: '', meaning: '逃脱；离开' },
      { word: 'king', phonetic: '/kɪŋ/', meaning: 'n. 君主；国王' },
      { word: 'artist', phonetic: '/ˈɑːtɪst/', meaning: 'n. 美术家；艺术家' },
      { word: 'quickly', phonetic: '/ˈkwɪkli/', meaning: 'adv. 快速地；很快' },
      { word: 'smile', phonetic: '/smaɪl/', meaning: 'v. 微笑 n. 微笑；笑容' },
      { word: 'all over', phonetic: '', meaning: '到处；遍及' },
      { word: 'ugly', phonetic: '/ˈʌɡli/', meaning: 'adj. 丑陋的；难看的' },
      { word: 'duckling', phonetic: '/ˈdʌklɪŋ/', meaning: 'n. 小鸭子' },
      { word: 'real', phonetic: '/rɪəl/', meaning: 'adj. 真的；真正的' },
      { word: 'laugh at', phonetic: '', meaning: '嘲笑' },
      { word: 'go away', phonetic: '', meaning: '走开' },
      { word: 'search', phonetic: '/sɜːtʃ/', meaning: 'v. 寻找；搜寻' },
      { word: 'search for', phonetic: '', meaning: '寻找' },
      { word: 'hen', phonetic: '/hen/', meaning: 'n. 母鸡' },
      { word: 'hopefully', phonetic: '/ˈhəʊpfəli/', meaning: 'adv. 有希望地' },
      { word: 'purr', phonetic: '/pɜː(r)/', meaning: 'v. （猫愉快时）发出呜呜声' },
      { word: 'lay', phonetic: '/leɪ/', meaning: 'v. (laid /leɪd/) 下（蛋）；放置；搁' },
      { word: 'swan', phonetic: '/swɒn/', meaning: 'n. 天鹅' },
      { word: 'feather', phonetic: '/ˈfeðə/', meaning: 'n. 羽毛' },
      { word: "to sb's surprise", phonetic: '', meaning: '出乎某人的意料' },
      { word: 'size', phonetic: '/saɪz/', meaning: 'n. 大小；尺寸' },
      { word: 'believe', phonetic: '/bɪˈliːv/', meaning: 'v. 相信；认为' },
      { word: 'only if', phonetic: '', meaning: '只有' },
      { word: 'fisherman', phonetic: '/ˈfɪʃəmən/', meaning: 'n. (pl. fishermen) 渔夫' },
      { word: 'fishing', phonetic: '/ˈfɪʃɪŋ/', meaning: 'n. 钓鱼；捕鱼' },
      { word: 'come out', phonetic: '', meaning: '出现；盛开' },
      { word: 'genie', phonetic: '/ˈdʒiːni/', meaning: 'n. 妖怪；鬼' },
      { word: 'die', phonetic: '/daɪ/', meaning: 'v. 死亡；消失' },
      { word: 'make a promise', phonetic: '', meaning: '许下诺言' },
      { word: 'someone', phonetic: '/ˈsʌmwʌn/', meaning: 'pron. 某人；有人' },
      { word: 'set', phonetic: '/set/', meaning: 'v. 使处于某种状况；使开始' },
      { word: 'set … free', phonetic: '', meaning: '释放' },
      { word: 'rich', phonetic: '/rɪtʃ/', meaning: 'adj. 富有的；富含……的' },
      { word: 'powerful', phonetic: '/ˈpaʊəfl/', meaning: 'adj. 强大的；有影响力的' },
      { word: 'anyone', phonetic: '/ˈeniwʌn/', meaning: 'pron. 任何人；某个人' },
      { word: 'instead of', phonetic: '', meaning: '而不是；代替' },
      { word: 'succeed in doing sth', phonetic: '', meaning: '成功做成某事' },
      { word: 'himself', phonetic: '/hɪmˈself/', meaning: 'pron. 他自己；他本人' },
      { word: 'in the end', phonetic: '', meaning: '最后；终究' },
    ]
  }
];
